### ISSUE TITLE
last 2 versions (3.1.22 and 3.1.23) of gitpython don't support python 3.6

### ISSUE THREAD

**Issue by xylar** [conda-forge/gitpython-feedstock#58]
The latest builds of `gitpython` should have `python >=3.7`:
https://github.com/gitpython-developers/GitPython/blob/3.1.22/setup.py#L96
https://github.com/gitpython-developers/GitPython/blob/3.1.23/setup.py#L96

This is causing trouble because these versions are using features not available in python 3.6:
```
$ conda create -y -n test python=3.6 gitpython
$ conda activate test
$ python -c "import git"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xylar/miniconda3/envs/test/lib/python3.6/site-packages/git/__init__.py", line 43, in <module>
    from git.objects import *               # @NoMove @IgnorePep8
  File "/home/xylar/miniconda3/envs/test/lib/python3.6/site-packages/git/objects/__init__.py", line 9, in <module>
    from .commit import *
  File "/home/xylar/miniconda3/envs/test/lib/python3.6/site-packages/git/objects/commit.py", line 15, in <module>
    from git.diff import Diffable
  File "/home/xylar/miniconda3/envs/test/lib/python3.6/site-packages/git/diff.py", line 8, in <module>
    from git.cmd import handle_process_output
  File "/home/xylar/miniconda3/envs/test/lib/python3.6/site-packages/git/cmd.py", line 6
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by xylar** [comment]
This kind of thing is one of the reasons I'm really not a fan of the automerge bot.

**Comment by ocefpaf** [comment]
> This kind of thing is one of the reasons I'm really not a fan of the automerge bot.

Yeah. Ideally we should have automerge only with a regenerated recipe from grayskull. I'll send PRs to mark them as broken and fix the recipe here. Thanks!
